In [1]:
def init():
    #所有文档
    docs = [
        'aa bb cc',
        'aa bb cc dd',
        'aa bb cc ee',
        'aa bb cc ee ee',
    ]

    #分词
    docs = [i.split(' ') for i in docs]

    #初始化字典
    words = []
    for doc in docs:
        for word in doc:
            if word not in words:
                words.append(word)

    return docs, words


docs, words = init()

docs, words

([['aa', 'bb', 'cc'],
  ['aa', 'bb', 'cc', 'dd'],
  ['aa', 'bb', 'cc', 'ee'],
  ['aa', 'bb', 'cc', 'ee', 'ee']],
 ['aa', 'bb', 'cc', 'dd', 'ee'])

In [2]:
import numpy as np


def get_tf():
    tf = np.zeros([len(docs), len(words)])

    #计算词频
    for i, doc in enumerate(docs):
        for word in doc:
            j = words.index(word)
            tf[i, j] += 1

    #tf = 词频 / 句子长度
    for i, doc in enumerate(docs):
        tf[i] /= len(doc)

    return tf


tf = get_tf()

tf

array([[0.33333333, 0.33333333, 0.33333333, 0.        , 0.        ],
       [0.25      , 0.25      , 0.25      , 0.25      , 0.        ],
       [0.25      , 0.25      , 0.25      , 0.        , 0.25      ],
       [0.2       , 0.2       , 0.2       , 0.        , 0.4       ]])

In [3]:
def get_idf():
    idf = np.zeros([len(words)])

    #求每个词出现的文档数
    for i, word in enumerate(words):
        idf[i] = sum([1 for doc in docs if word in doc])

    #文档总数除以每个词出现的文档数
    #相当于求每个词的代表能力,这个数最小是1,最大是文档数量
    idf = len(docs) / idf

    #idf是非负的,并且>=1,取对数后最小是0
    idf = np.log(idf)

    return idf


idf = get_idf()

idf

array([0.        , 0.        , 0.        , 1.38629436, 0.69314718])

In [4]:
#综合考虑tf和idf,得到每个词对应每个文档的代表能力
tf_idf = tf * idf

tf_idf

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.34657359, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.1732868 ],
       [0.        , 0.        , 0.        , 0.        , 0.27725887]])